engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.ctp"
exclude_paths:
 - "bin/"
 - "logs/"
 - "plugins/"
 - "tests/"
 - "tmp/"
 - "vendor/"
 - "webroot/"
 - "**/*"
 - "!**/*.php"
 - "!**/*.ctp"
 - "/code/src/Template/Element/website"
 - "/webroot/emojione/*"
