engines:
  phpmd:
    enabled: true
    checks:
        # wish I could just turn this one off
        # for key pairs. but 75% of the time, it
        # just returns that a local var in a foreach
        # key pair was unused. darn.
        UnusedLocalVariable:
            enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
 - "bin/"
 - "logs/"
 - "plugins/"
 - "tests/"
 - "tmp/"
 - "vendor/"
 - "webroot/"
