engines:
  phpmd:
    enabled: true
    checks:
      UnusedLocalVariable:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.ctp"
exclude_paths:
 - "bin/"
 - "logs/"
 - "plugins/"
 - "tests/"
 - "tmp/"
 - "vendor/"
 - "webroot/"
