language: php

sudo: false

php:
  - 5.6

services:
  - mysql

before_script:
  - sh -c "mysql -e 'CREATE DATABASE IF NOT EXISTS okbvtfr_testing;'"
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --error-severity=1 --warning-severity=0 --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot"
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

notifications:
  email: false
  slack: cber:ZeUxtjnpHNEYCkMtUBhskwXl

addons:
  code_climate:
    repo_token: 234563002b595ccee04d56dc2c0b39848d0c4af9cdda1104187bbd3241fd4c03

after_success:
  - vendor/bin/test-reporter
